### PR TITLE
Update recipe to include trackpy requirement

### PR DESCRIPTION
**Pull request by TomSlater**
Added the dependency trackpy to the conda recipe. This is in ParticleSpy's dependencies in setup.py.

### CODE REVIEW

**Review by tschoonj — APPROVED** [review]
I am fine with this.

Feel free to add yourself as a maintainer of this package, since you appear to be its main developer.

**Comment by TomSlater** [comment]
Thanks Tom. I take it you meant add to the maintainers list in this PR?

**Comment by tschoonj** [comment]
You will need to add your GitHub username to the end of the meta.yaml file.

**Comment by tschoonj** [comment]
Also please remove your last commit. Thanks!

**Comment by tschoonj** [comment]
@conda-forge-bot please rerender

**Comment by tschoonj** [comment]
@conda-forge-admin please rerender

**Comment by tschoonj** [comment]
I just realised that you didn't bump the build number. Now the packages on conda-forge won't get updated with the added dependency. 😢 

Do you plan on making a new release of particlespy soon? Otherwise you will need to create a new PR to ensure new packages are uploaded.

Apologies, should have spotted this earlier!

**Comment by TomSlater** [comment]
I need to do a quick bug fix this week so will do a new release. I should update the conda recipe to include some files too though (probably before the release on pypi), so will also bump the build number then.

**Comment by tschoonj** [comment]
Ok sounds good. By the way, shortly after you push your new release to PyPI, you can expect to see an automagically generated PR here that will bump the recipe to the same new release.

**Pull request merged**
